
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class EmployeeDetails extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeDetails
     */
    public EmployeeDetails() {
       
        initComponents();
        showTableData();     
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField_Age = new javax.swing.JTextField();
        jTextField_Mother_Name = new javax.swing.JTextField();
        jTextField_Father_Name = new javax.swing.JTextField();
        jTextField_Employee_Name = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField_Job = new javax.swing.JTextField();
        jTextField_Employee_Phone_Number = new javax.swing.JTextField();
        jTextField_Employee_Address = new javax.swing.JTextField();
        jTextField_Salary = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee_ID", "Employee_Name", "Father_Name", "Mother_Name", "Age", "Gender", "Job", "Employee_Phone_Number", "Employee_Address	", "Salary", "Password"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1280, 240));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 620, 110, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Update.png"))); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 620, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 620, 130, 40));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 204, 0));
        jLabel16.setText("Employee ID");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 204, 0));
        jLabel19.setText("Employee's Name");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 204, 0));
        jLabel20.setText("Father's Name");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 204, 0));
        jLabel21.setText("Mother's Name");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, -1, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 204, 0));
        jLabel13.setText("Age");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 204, 0));
        jLabel14.setText("Gender");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 600, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, 191, 35));
        jPanel2.add(jTextField_Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 191, 33));
        jPanel2.add(jTextField_Mother_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 191, 33));

        jTextField_Father_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Father_NameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_Father_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 191, 33));
        jPanel2.add(jTextField_Employee_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 191, 33));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 191, 33));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BACK");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 204, 0));
        jLabel15.setText("Job");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 204, 0));
        jLabel11.setText("Phone Number");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 204, 0));
        jLabel18.setText("Employee's Address");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, -1, -1));

        jTextField_Job.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_JobActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_Job, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 320, 191, 33));

        jTextField_Employee_Phone_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Employee_Phone_NumberActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_Employee_Phone_Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 380, 191, 33));

        jTextField_Employee_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Employee_AddressActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_Employee_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 430, 191, 33));

        jTextField_Salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SalaryActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_Salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 480, 191, 33));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 530, 191, 35));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Salary");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, -1, -1));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 204, 0));
        jLabel22.setText("Password");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 530, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField_SalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SalaryActionPerformed

    private void jTextField_Employee_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Employee_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Employee_AddressActionPerformed

    private void jTextField_Employee_Phone_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Employee_Phone_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Employee_Phone_NumberActionPerformed

    private void jTextField_JobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_JobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_JobActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        
       AdminDashboard ad= new AdminDashboard();
       ad.show();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField_Father_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Father_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Father_NameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        String Employee_ID = jTextField1.getText();

        Connection con;
        PreparedStatement pst;

        try {
            con = Connection1.createConnection();
            pst = con.prepareStatement("DELETE FROM employees WHERE Employee_ID = ?");
            pst.setString(1, Employee_ID);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "DELETE SUCCESFULLY");

        } catch (SQLException ex) {
            Logger.getLogger(AdminLoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        showTableData();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String Employee_ID = jTextField1.getText();
        String Employee_Name= jTextField_Employee_Name.getText();
        String Father_Name = jTextField_Father_Name.getText();
        String Mother_Name = jTextField_Mother_Name.getText();
        String Age = jTextField_Age.getText();
        String Gender = (String) jComboBox1.getSelectedItem();
        String Job = jTextField_Job.getText();
        String Employee_Phone_Number = jTextField_Employee_Phone_Number.getText();
        String Employee_Address= jTextField_Employee_Address.getText();
        String Salary = jTextField_Salary.getText();
        String Password = String.valueOf(jPasswordField1.getPassword());

        Connection con;
        PreparedStatement pst;

        try {
            con =  Connection1.createConnection();
            pst = con.prepareStatement("Update employees SET Employee_Name = ?,Father_Name = ?, Mother_Name = ?, Age = ?, Gender=?,Job=?,Employee_Phone_Number=?,Employee_Address = ?,Salary=?, Password = ? WHERE Employee_ID = ?");

            pst.setString(11, Employee_ID);
            pst.setString(1, Employee_Name);
            pst.setString(2, Father_Name);
            pst.setString(3, Mother_Name);
            pst.setString(4, Age);
            pst.setString(5, Gender);
            pst.setString(6, Job);
            pst.setString(7, Employee_Phone_Number);
            pst.setString(8, Employee_Address);
            pst.setString(9, Salary);
            pst.setString(10, Password);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "UPDATE SUCCESFULLY");
        } catch (SQLException ex) {
            System.out.println(ex);
        }

        showTableData();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String Employee_ID = jTextField1.getText();
        String Job = jTextField_Job.getText();
        String Salary = jTextField_Salary.getText();
        Connection con;
        PreparedStatement pst;

        try {
            con = Connection1.createConnection();
            pst = con.prepareStatement("Update employees SET Job = ?,Salary=? WHERE Employee_ID = ?");

            pst.setString(3, Employee_ID);
            pst.setString(1, Job);
            pst.setString(2,Salary);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "INSERT SUCCESFULLY");
        } catch (SQLException ex) {
            Logger.getLogger(AdminLoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        showTableData();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public void showTableData(){
 
        Connection con;
     PreparedStatement pst;
     ResultSet rs;
     
      try {
            con = Connection1.createConnection();
            pst = con.prepareStatement("SELECT *FROM employees");
                       
           rs= pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
           
            
       } catch (SQLException ex) {
            Logger.getLogger(AdminLoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_Age;
    private javax.swing.JTextField jTextField_Employee_Address;
    private javax.swing.JTextField jTextField_Employee_Name;
    private javax.swing.JTextField jTextField_Employee_Phone_Number;
    private javax.swing.JTextField jTextField_Father_Name;
    private javax.swing.JTextField jTextField_Job;
    private javax.swing.JTextField jTextField_Mother_Name;
    private javax.swing.JTextField jTextField_Salary;
    // End of variables declaration//GEN-END:variables
}
