
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class EmployeePage extends javax.swing.JFrame {

    /**
     * Creates new form EmployeePage
     */
    public EmployeePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Mother_Name = new javax.swing.JLabel();
        jLabelFather_Name = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel_User_Name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Employee_Name = new javax.swing.JTextField();
        jLabel_Phone_Number = new javax.swing.JLabel();
        jTextField_Employee_Phone_Number = new javax.swing.JTextField();
        jLabel_User_Address = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField_Employee_Address = new javax.swing.JTextField();
        jTextFieldPassword = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel_Password = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Mother_Name = new javax.swing.JTextField();
        jTextField_Father_Name = new javax.swing.JTextField();
        jTextField_Age = new javax.swing.JTextField();
        jTextField_Job = new javax.swing.JTextField();
        jTextField_Gender = new javax.swing.JTextField();
        jLabel_Age = new javax.swing.JLabel();
        jLabel_Job = new javax.swing.JLabel();
        jLabel_Gender = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Mother_Name.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel_Mother_Name.setForeground(new java.awt.Color(255, 153, 0));
        jLabel_Mother_Name.setText("Mother's Name");
        getContentPane().add(jLabel_Mother_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 266, -1, -1));

        jLabelFather_Name.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabelFather_Name.setForeground(new java.awt.Color(255, 153, 0));
        jLabelFather_Name.setText("Father's Name");
        getContentPane().add(jLabelFather_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 216, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 80, 191, 33));

        jLabel_User_Name.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel_User_Name.setForeground(new java.awt.Color(255, 153, 0));
        jLabel_User_Name.setText("Employee's Name");
        getContentPane().add(jLabel_User_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 166, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Employee ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 83, -1, -1));
        getContentPane().add(jTextField_Employee_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 166, 191, 33));

        jLabel_Phone_Number.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel_Phone_Number.setForeground(new java.awt.Color(255, 153, 0));
        jLabel_Phone_Number.setText("Phone Number");
        getContentPane().add(jLabel_Phone_Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 168, -1, -1));

        jTextField_Employee_Phone_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Employee_Phone_NumberActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Employee_Phone_Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(998, 166, 191, 33));

        jLabel_User_Address.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel_User_Address.setForeground(new java.awt.Color(255, 153, 0));
        jLabel_User_Address.setText("Employee's Address");
        getContentPane().add(jLabel_User_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 227, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButton1.setText("  Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, -1, -1));
        jPanel1.add(jTextField_Employee_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 220, 191, 33));

        jTextFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 280, 191, 35));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 340, 191, 32));

        jLabel_Password.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel_Password.setForeground(new java.awt.Color(255, 153, 0));
        jLabel_Password.setText("Password");
        jPanel1.add(jLabel_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Salary");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("HOME");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 20, -1, -1));
        jPanel1.add(jTextField_Mother_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 191, 33));

        jTextField_Father_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Father_NameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_Father_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 191, 33));

        jTextField_Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AgeActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 191, 33));

        jTextField_Job.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_JobActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_Job, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 191, 33));

        jTextField_Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_GenderActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 191, 33));

        jLabel_Age.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel_Age.setForeground(new java.awt.Color(255, 153, 0));
        jLabel_Age.setText("Age");
        jPanel1.add(jLabel_Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        jLabel_Job.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel_Job.setForeground(new java.awt.Color(255, 153, 0));
        jLabel_Job.setText("Job");
        jPanel1.add(jLabel_Job, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        jLabel_Gender.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel_Gender.setForeground(new java.awt.Color(255, 153, 0));
        jLabel_Gender.setText("Gender");
        jPanel1.add(jLabel_Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Employee.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 820));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_GenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_GenderActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField_AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AgeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String Employee_ID= jTextField1.getText();
        
        Connection con;
     PreparedStatement pst;
     ResultSet rs;
        
        try {
            con = Connection1.createConnection();
            pst = con.prepareStatement("SELECT *FROM employees WHERE Employee_ID = ?");
            pst.setString(1, Employee_ID);
            rs=pst.executeQuery();
           if(rs.next()){
           String add1=rs.getString("Employee_Name");
           jTextField_Employee_Name.setText(add1);
           String add2=rs.getString("Father_Name");
           jTextField_Father_Name.setText(add2);
           String add3=rs.getString("Mother_Name");
           jTextField_Mother_Name.setText(add3);
           
           String add4=rs.getString("Age");
           jTextField_Age.setText(add4);           
           String add5=rs.getString("Gender");
           jTextField_Gender.setText(add5);
           String add6=rs.getString("Job");
           jTextField_Job.setText(add6);
           String add7=rs.getString("Employee_Phone_Number");
           jTextField_Employee_Phone_Number.setText(add7);
           String add8=rs.getString("Employee_Address");
            jTextField_Employee_Address.setText(add8);
           String add9=rs.getString("Password");
            jTextFieldPassword.setText(add9);
           String add10=rs.getString("Salary");
            jTextField2.setText(add10);
          
           JOptionPane.showMessageDialog(null, "SEARCH SUCCESFULLY");
           }
                    
            
            
       } catch (SQLException ex) {
            Logger.getLogger(AdminLoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPasswordActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        
        HomePage h=new HomePage();
        h.show();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jTextField_Father_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Father_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Father_NameActionPerformed

    private void jTextField_JobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_JobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_JobActionPerformed

    private void jTextField_Employee_Phone_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Employee_Phone_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Employee_Phone_NumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelFather_Name;
    private javax.swing.JLabel jLabel_Age;
    private javax.swing.JLabel jLabel_Gender;
    private javax.swing.JLabel jLabel_Job;
    private javax.swing.JLabel jLabel_Mother_Name;
    private javax.swing.JLabel jLabel_Password;
    private javax.swing.JLabel jLabel_Phone_Number;
    private javax.swing.JLabel jLabel_User_Address;
    private javax.swing.JLabel jLabel_User_Name;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextField_Age;
    private javax.swing.JTextField jTextField_Employee_Address;
    private javax.swing.JTextField jTextField_Employee_Name;
    private javax.swing.JTextField jTextField_Employee_Phone_Number;
    private javax.swing.JTextField jTextField_Father_Name;
    private javax.swing.JTextField jTextField_Gender;
    private javax.swing.JTextField jTextField_Job;
    private javax.swing.JTextField jTextField_Mother_Name;
    // End of variables declaration//GEN-END:variables
}
