import java.sql.Connection; 
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


import javax.swing.JOptionPane;
;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class UserRegPage extends javax.swing.JFrame {

    /**
     * Creates new form registration
     */
    public UserRegPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabelFather_Name = new javax.swing.JLabel();
        jLabel_Mother_Name = new javax.swing.JLabel();
        jLabel_Age = new javax.swing.JLabel();
        jLabel_Gender = new javax.swing.JLabel();
        jLabel_Job = new javax.swing.JLabel();
        jLabel_User_Name = new javax.swing.JLabel();
        jLabel_Phone_Number = new javax.swing.JLabel();
        jLabel_User_Address = new javax.swing.JLabel();
        jTextField_User_Name = new javax.swing.JTextField();
        jTextField_Father_Name = new javax.swing.JTextField();
        jTextField_Mother_Name = new javax.swing.JTextField();
        jTextField_Age = new javax.swing.JTextField();
        jTextField_Job = new javax.swing.JTextField();
        jTextField_User_Phone_Number = new javax.swing.JTextField();
        jTextField_User_Address = new javax.swing.JTextField();
        jComboBox_Gender = new javax.swing.JComboBox<>();
        jLabel_Password = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1_Confirm = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Marcellus", 1, 24)); // NOI18N
        jLabel10.setText("USER REGISTRATION");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, -1, -1));

        jLabelFather_Name.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabelFather_Name.setText("Father's Name");
        jPanel1.add(jLabelFather_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, -1, -1));

        jLabel_Mother_Name.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel_Mother_Name.setText("Mother's Name");
        jPanel1.add(jLabel_Mother_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 290, -1, -1));

        jLabel_Age.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel_Age.setText("Age");
        jPanel1.add(jLabel_Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, -1, -1));

        jLabel_Gender.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel_Gender.setText("Gender");
        jPanel1.add(jLabel_Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, -1, -1));

        jLabel_Job.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel_Job.setText("Job");
        jPanel1.add(jLabel_Job, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, -1, -1));

        jLabel_User_Name.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel_User_Name.setText("User's Name");
        jPanel1.add(jLabel_User_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, -1, -1));

        jLabel_Phone_Number.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel_Phone_Number.setText("Phone Number");
        jPanel1.add(jLabel_Phone_Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, -1, -1));

        jLabel_User_Address.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel_User_Address.setText("User's Address");
        jPanel1.add(jLabel_User_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 550, -1, -1));
        jPanel1.add(jTextField_User_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 190, 191, 33));
        jPanel1.add(jTextField_Father_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 230, 191, 33));
        jPanel1.add(jTextField_Mother_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 280, 191, 33));
        jPanel1.add(jTextField_Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 330, 191, 33));
        jPanel1.add(jTextField_Job, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 430, 191, 33));
        jPanel1.add(jTextField_User_Phone_Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 480, 191, 33));
        jPanel1.add(jTextField_User_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 540, 191, 33));

        jComboBox_Gender.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jComboBox_Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        jPanel1.add(jComboBox_Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 380, 191, 35));

        jLabel_Password.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel_Password.setText("Password");
        jPanel1.add(jLabel_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 600, -1, -1));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 590, 191, 35));

        jLabel1_Confirm.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel1_Confirm.setText("CONFIRM");
        jLabel1_Confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_ConfirmMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1_Confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 640, -1, -1));

        jLabel3.setFont(new java.awt.Font("Marcellus", 1, 24)); // NOI18N
        jLabel3.setText("HOME");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UserReg.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        
       HomePage h= new HomePage();
       h.show();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel1_ConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_ConfirmMouseClicked
       
     // TODO add your handling code here:
       String User_Name = jTextField_User_Name.getText();
       String Father_Name = jTextField_Father_Name.getText();
       String Mother_Name = jTextField_Mother_Name.getText();
       String Age = jTextField_Age.getText();
       String Gender = (String) jComboBox_Gender.getSelectedItem();
       String Job = jTextField_Job.getText();
       String User_Phone_Number = jTextField_User_Phone_Number.getText();
       String User_Address = jTextField_User_Address.getText();
       String Password = String.valueOf(jPasswordField1.getPassword());
      
           
     
     Connection con;
     PreparedStatement pst;
     
     
     
        try {
            con =  Connection1.createConnection();
            pst = con.prepareStatement("insert Into users(User_Name,Father_Name,Mother_Name,Age,Gender,Job,User_Phone_Number,User_Address,Password) Values(?,?,?,?,?,?,?,?,?)");
     pst.setString(1, User_Name);
     pst.setString(2, Father_Name);
     pst.setString(3, Mother_Name);
     pst.setString(4, Age);
     pst.setString(5, Gender);
     pst.setString(6, Job);
     pst.setString(7, User_Phone_Number);
     pst.setString(8, User_Address);
     pst.setString(9, Password);
          pst.executeUpdate();
          JOptionPane.showMessageDialog(null, "REGESTER SUCCESFULLY");
        } catch (SQLException ex) {
           
           System.out.println(ex);
        }
          
          
                
       
    }//GEN-LAST:event_jLabel1_ConfirmMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRegPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_Gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel1_Confirm;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFather_Name;
    private javax.swing.JLabel jLabel_Age;
    private javax.swing.JLabel jLabel_Gender;
    private javax.swing.JLabel jLabel_Job;
    private javax.swing.JLabel jLabel_Mother_Name;
    private javax.swing.JLabel jLabel_Password;
    private javax.swing.JLabel jLabel_Phone_Number;
    private javax.swing.JLabel jLabel_User_Address;
    private javax.swing.JLabel jLabel_User_Name;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField_Age;
    private javax.swing.JTextField jTextField_Father_Name;
    private javax.swing.JTextField jTextField_Job;
    private javax.swing.JTextField jTextField_Mother_Name;
    private javax.swing.JTextField jTextField_User_Address;
    private javax.swing.JTextField jTextField_User_Name;
    private javax.swing.JTextField jTextField_User_Phone_Number;
    // End of variables declaration//GEN-END:variables
}
