
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
//import javax.swing.JOptionPane;

//import java.sql.*;
//import Project.ConnectionProvider;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class UserDetails extends javax.swing.JFrame {

    
    /**
     * Creates new form UserDetails
     */
    public UserDetails() {
        initComponents();
      
       showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel_User_Name = new javax.swing.JLabel();
        jLabelFather_Name = new javax.swing.JLabel();
        jLabel_Mother_Name = new javax.swing.JLabel();
        jLabel_Age = new javax.swing.JLabel();
        jLabel_Gender = new javax.swing.JLabel();
        jLabel_Job = new javax.swing.JLabel();
        jTextField_Job = new javax.swing.JTextField();
        jComboBox_Gender = new javax.swing.JComboBox<>();
        jTextField_Age = new javax.swing.JTextField();
        jTextField_Mother_Name = new javax.swing.JTextField();
        jTextField_Father_Name = new javax.swing.JTextField();
        jTextField_User_Name = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel_Phone_Number = new javax.swing.JLabel();
        jTextField_User_Phone_Number = new javax.swing.JTextField();
        jTextField_User_Address = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_Password = new javax.swing.JLabel();
        jLabel_User_Address = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 600, 120, 40));

        jButton2.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Update.png"))); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 600, -1, -1));

        jButton3.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 600, 130, 40));

        jLabel1.setBackground(new java.awt.Color(255, 231, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jLabel_User_Name.setBackground(new java.awt.Color(255, 231, 0));
        jLabel_User_Name.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel_User_Name.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_User_Name.setText("User's Name");
        jPanel1.add(jLabel_User_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jLabelFather_Name.setBackground(new java.awt.Color(255, 231, 0));
        jLabelFather_Name.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabelFather_Name.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFather_Name.setText("Father's Name");
        jPanel1.add(jLabelFather_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        jLabel_Mother_Name.setBackground(new java.awt.Color(255, 231, 0));
        jLabel_Mother_Name.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel_Mother_Name.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Mother_Name.setText("Mother's Name");
        jPanel1.add(jLabel_Mother_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        jLabel_Age.setBackground(new java.awt.Color(255, 231, 0));
        jLabel_Age.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel_Age.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Age.setText("Age");
        jPanel1.add(jLabel_Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        jLabel_Gender.setBackground(new java.awt.Color(255, 231, 0));
        jLabel_Gender.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel_Gender.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Gender.setText("Gender");
        jPanel1.add(jLabel_Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, -1, -1));

        jLabel_Job.setBackground(new java.awt.Color(255, 231, 0));
        jLabel_Job.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel_Job.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Job.setText("Job");
        jPanel1.add(jLabel_Job, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, -1, -1));

        jTextField_Job.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_JobActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_Job, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, 191, 33));

        jComboBox_Gender.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jComboBox_Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        jPanel1.add(jComboBox_Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 191, 35));

        jTextField_Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AgeActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 191, 33));
        jPanel1.add(jTextField_Mother_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 191, 33));
        jPanel1.add(jTextField_Father_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 191, 33));
        jPanel1.add(jTextField_User_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 191, 33));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 191, 33));

        jLabel_Phone_Number.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel_Phone_Number.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Phone_Number.setText("Phone Number");
        jPanel1.add(jLabel_Phone_Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, -1, -1));
        jPanel1.add(jTextField_User_Phone_Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 250, 191, 33));
        jPanel1.add(jTextField_User_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 310, 191, 33));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 360, 191, 34));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 420, 191, 32));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 470, 191, 34));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Monthly Cost");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seat NO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, -1, -1));

        jLabel_Password.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel_Password.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Password.setText("Password");
        jPanel1.add(jLabel_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, -1, -1));

        jLabel_User_Address.setFont(new java.awt.Font("Marcellus", 1, 18)); // NOI18N
        jLabel_User_Address.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_User_Address.setText("User's Address");
        jPanel1.add(jLabel_User_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, -1, -1));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "User_ID", "User_Name", "Father_Name", "Mother_Name", "Age", "Gender", "Job", "User_Phone_Number", "User_Address	", "Seat_No", "Password", "Monthly_Cost"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 1210, 170));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setText("BACK");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 231, 0));
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 820));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       String User_ID = jTextField1.getText();
       String Seat_No = jTextField2.getText();
      String Monthly_Cost = jTextField3.getText();
        Connection con;
        PreparedStatement pst;
       
        
        try {
            con = Connection1.createConnection();
            pst = con.prepareStatement("Update users SET Seat_No = ?,Monthly_Cost=? WHERE User_ID = ?");
            
            pst.setString(3, User_ID);
           pst.setString(1, Seat_No);
            pst.setString(2,Monthly_Cost);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "INSERT SUCCESFULLY");
       } catch (SQLException ex) {
            Logger.getLogger(AdminLoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
         
showTableData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        String User_ID = jTextField1.getText();
        String User_Name= jTextField_User_Name.getText();
       String Father_Name = jTextField_Father_Name.getText();
       String Mother_Name = jTextField_Mother_Name.getText();
       String Age = jTextField_Age.getText();
       String Gender = (String) jComboBox_Gender.getSelectedItem();
       String Job = jTextField_Job.getText();
       String User_Phone_Number = jTextField_User_Phone_Number.getText();
       String User_Address = jTextField_User_Address.getText();
       String Password = String.valueOf(jPasswordField1.getPassword());
       String Seat_No = jTextField2.getText();
       String Monthly_Cost = jTextField3.getText();
       
       
       
     Connection con;
     PreparedStatement pst;
     
     
     
        try {
            con =  Connection1.createConnection();
            pst = con.prepareStatement("Update users SET User_Name = ?,Father_Name = ?, Mother_Name = ?, Age = ?, Gender=?,Job=?,User_Phone_Number=?,User_Address = ?,Password=?, Seat_No = ?, Monthly_Cost= ? WHERE User_ID = ?");
     
            pst.setString(12, User_ID);
            pst.setString(1, User_Name);
     pst.setString(2, Father_Name);
     pst.setString(3, Mother_Name);
     pst.setString(4, Age);
     pst.setString(5, Gender);
     pst.setString(6, Job);
     pst.setString(7, User_Phone_Number);
     pst.setString(8, User_Address);
     pst.setString(9, Password);
     pst.setString(10, Seat_No);
     pst.setString(11, Monthly_Cost);
         pst.executeUpdate();
     JOptionPane.showMessageDialog(null, "UPDATE SUCCESFULLY");
        } catch (SQLException ex) {
           
           System.out.println(ex);
        }
          
       showTableData();                         
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        String User_ID = jTextField1.getText();
    
        
        Connection con;
     PreparedStatement pst;
        
        try {
            con = Connection1.createConnection();
            pst = con.prepareStatement("DELETE FROM users WHERE User_ID = ?");
            pst.setString(1, User_ID);
           
                    pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "DELETE SUCCESFULLY");
            
       } catch (SQLException ex) {
            Logger.getLogger(AdminLoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        showTableData(); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField_AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AgeActionPerformed

    private void jTextField_JobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_JobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_JobActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
               
       AdminDashboard ad=new AdminDashboard();
       ad.show();
    }//GEN-LAST:event_jLabel4MouseClicked
 
    
    public void showTableData(){
 
        Connection con;
     PreparedStatement pst;
     ResultSet rs;
     
      try {
            con = Connection1.createConnection();
            pst = con.prepareStatement("SELECT *FROM users");
                       
           rs= pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
           
            
       } catch (SQLException ex) {
            Logger.getLogger(AdminLoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    
 
 }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox_Gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelFather_Name;
    private javax.swing.JLabel jLabel_Age;
    private javax.swing.JLabel jLabel_Gender;
    private javax.swing.JLabel jLabel_Job;
    private javax.swing.JLabel jLabel_Mother_Name;
    private javax.swing.JLabel jLabel_Password;
    private javax.swing.JLabel jLabel_Phone_Number;
    private javax.swing.JLabel jLabel_User_Address;
    private javax.swing.JLabel jLabel_User_Name;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField_Age;
    private javax.swing.JTextField jTextField_Father_Name;
    private javax.swing.JTextField jTextField_Job;
    private javax.swing.JTextField jTextField_Mother_Name;
    private javax.swing.JTextField jTextField_User_Address;
    private javax.swing.JTextField jTextField_User_Name;
    private javax.swing.JTextField jTextField_User_Phone_Number;
    // End of variables declaration//GEN-END:variables
}
